name: license_view_fluent_ui
description: "Creates a view that shows licenses for software used
  by the application."
version: 1.0.0
homepage: https://github.com/DamianAldair/license_view_fluent_ui
repository: https://github.com/DamianAldair/license_view_fluent_ui

environment:
  sdk: '>=2.19.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  fluent_ui: ^4.9.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any
