name: Publish to Pub.dev

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  build:
    name: Publish
    runs-on: ubuntu-latest

    steps:
      - name: Check out
        uses: actions/checkout@main

      - name: Install Flutter
        uses: subosito/flutter-action@main
        with:
          channel: "stable"

      - name: Install dependencies
        run: flutter pub get

      - name: Check Flutter version
        run: flutter --version

      - name: Analyze project source
        run: flutter analyze

      - name: Format code
        run: dart format --fix

      - name: Check Publish Warnings
        run: dart pub publish --dry-run

      - name: Publish
        uses: k-paxian/dart-package-publisher@master
        with:
          credentialJson: ${{ secrets.CREDENTIAL_JSON }}
          flutter: true
          skipTests: true
